import { NextRequest, NextResponse } from 'next/server';

const MOONSHOT_API_KEY = process.env.MOONSHOT_API_KEY;

export async function POST(request: NextRequest) {
  try {
    const { idea, scores } = await request.json();

    if (!idea) {
      return NextResponse.json({ error: 'No idea provided' }, { status: 400 });
    }

    const prompt = `You are the gene extractor for an evolutionary startup idea breeder.

HOW THIS WORKS:
- Ideas are generated by combining "genes" (concept fragments) from a pool
- Your job is to extract new genes from this idea to add to the pool
- Good genes are abstract enough to recombine with other concepts
- The genes you extract will be used to generate future ideas
- This is how the system learns and evolves

THE IDEA:
Name: ${idea.name}
Description: ${idea.description}
Hook: ${idea.hook}

SCORES:
Utility: ${scores.utility || scores.virality}/10
Simplicity: ${scores.simplicity}/10
Economics: ${scores.economics || scores.immediacy}/10
Frequency: ${scores.frequency || scores.recurrence}/10
Uniqueness: ${scores.uniqueness || scores.urgency}/10
Leverage: ${scores.leverage || 5}/10

YOUR TASK:
Extract 3-5 reusable concept fragments. Think about:
- What PROBLEM does this solve? (extract the problem as a gene)
- What AUDIENCE is this for? (extract the audience as a gene)
- What MECHANISM makes it work? (extract the mechanism)
- What makes it DIFFERENT? (extract the differentiator)

Good genes are things like: "automates tedious paperwork", "busy parents", "AI reads documents for you", "replaces expensive professionals"

Respond with ONLY valid JSON:
{
  "genes": ["gene 1", "gene 2", "gene 3", ...]
}`;

    const response = await fetch('https://api.moonshot.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${MOONSHOT_API_KEY}`
      },
      body: JSON.stringify({
        model: 'kimi-k2-0905-preview',
        messages: [
          { role: 'system', content: 'You are a concept analyst. Always respond with valid JSON only.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
        max_tokens: 200
      })
    });

    if (!response.ok) {
      const error = await response.text();
      console.error('Moonshot API error:', error);
      return NextResponse.json({ error: 'AI service error' }, { status: 500 });
    }

    const data = await response.json();
    const content = data.choices[0].message.content;

    let result;
    try {
      const cleanContent = content.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
      result = JSON.parse(cleanContent);
    } catch {
      console.error('Failed to parse:', content);
      return NextResponse.json({ error: 'Failed to parse AI response' }, { status: 500 });
    }

    return NextResponse.json({ genes: result.genes });

  } catch (error) {
    console.error('Extract error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
