-- API Ingestion Queue for background processing
CREATE TABLE IF NOT EXISTS api_ingestion_queue (
  id serial PRIMARY KEY,
  api_name text NOT NULL UNIQUE,
  status text DEFAULT 'pending', -- pending, processing, completed, failed
  attempts int DEFAULT 0,
  result_hook text,
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone
);

-- Index for finding pending items
CREATE INDEX idx_api_queue_status ON api_ingestion_queue(status);

-- Insert the curated API list
INSERT INTO api_ingestion_queue (api_name) VALUES
  ('NOAA Storm Events Database API'),
  ('EPA Toxics Release Inventory API'),
  ('PACER Federal Court Records API'),
  ('FDA Food Recall API'),
  ('Census Bureau ACS API'),
  ('SEC EDGAR API'),
  ('FEC Campaign Finance API'),
  ('Crunchbase API'),
  ('FRED Federal Reserve Economic Data API'),
  ('Alpha Vantage Stock API'),
  ('Yahoo Finance API'),
  ('CoinGecko Cryptocurrency API'),
  ('OpenCorporates API'),
  ('IEX Cloud API'),
  ('PubMed API'),
  ('ClinicalTrials.gov API'),
  ('OpenFDA API'),
  ('UniProt Protein Database API'),
  ('ChEMBL Drug Database API'),
  ('Human Genome API'),
  ('CDC Wonder API'),
  ('OpenStreetMap Overpass API'),
  ('NASA Earthdata API'),
  ('USGS National Map API'),
  ('OpenSky Flight Tracking API'),
  ('GeoNames API'),
  ('What3Words API'),
  ('GitLab API'),
  ('npm Registry API'),
  ('PyPI API'),
  ('Stack Exchange API'),
  ('Hacker News API'),
  ('Product Hunt API'),
  ('GDELT Global News API'),
  ('Wikimedia API'),
  ('TMDB Movie Database API'),
  ('YouTube Data API'),
  ('Reddit API'),
  ('Hugging Face API'),
  ('OpenAI API'),
  ('Replicate API'),
  ('Clarifai API'),
  ('OpenWeatherMap API'),
  ('Weather.gov API'),
  ('AirNow Air Quality API'),
  ('Sunrise-Sunset API'),
  ('Twilio API'),
  ('SendGrid API'),
  ('Discord API'),
  ('Slack API'),
  ('Cloudflare API'),
  ('AWS SDK'),
  ('Stripe API'),
  ('Plaid API'),
  ('OpenLibrary API'),
  ('Chronicling America Historic Newspapers API'),
  ('NASA Astronomy Picture of the Day API'),
  ('SpaceX API'),
  ('Pokemon API'),
  ('Open Food Facts API'),
  ('Open Brewery DB API'),
  ('Dog CEO API'),
  ('Cat Facts API'),
  ('Random User Generator API')
ON CONFLICT (api_name) DO NOTHING;
